name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install flake8 (linter)
        run: pip install flake8

      - name: Run linting
        run: flake8 .

      - name: Run tests
        run: |
          pip install pytest
          pytest
